com/stencyl/Engine.hx, com/stencyl/behavior/Script.hx, com/stencyl/graphics/SheetAnimation.hx, com/stencyl/graphics/shaders/PostProcess.hx, com/stencyl/graphics/shaders/Shader.hx, com/stencyl/models/Actor.hx, com/stencyl/models/Scene.hx
Currently HTML5 only works with chrome (not firefox), but this modifies files across multiple locations to allow these games to be built without presenting an error
=> Fixed building for html5

com/stencyl/behavior/Script.hx, com/stencyl/graphics/BitmapAnimation.hx, com/stencyl/models/Actor.hx
I modified a couple of files to allow the tint filter to work on html5. I am working on the others as they should follow a similar principle.
=> HTML5 tint filter

com/stencyl/graphics/BitmapAnimation.hx, com/stencyl/graphics/fonts/BitmapFont.hx, com/stencyl/utils/ColorMatrix.hx
I also added support for fonts with opacity on html5 and fixed a very strange rendering bug
=> Fixed the broken filters on html5 (whoops)

com/stencyl/Input.hx, com/stencyl/graphics/BitmapAnimation.hx
One of my updates messed up rendering on flash - this fixes it.
=> Fixed created flash bug

Universal.hx
Fix the issue described here:
http://community.stencyl.com/index.php?issue=226.0
Done by reading in the selected scales depending on the target from game.xml.
=> Fix unselected scales being used

com/stencyl/models/scene/Layer.hx
Fix to Merrak's issue here:
http://community.stencyl.com/index.php/topic,46780.0.html
=> Fix slight jitter when scrolling (camera centre)

com/stencyl/Engine.hx
Original issue described and demonstrated here:
http://community.stencyl.com/index.php/topic,47073.msg261911.html#new
=> Fix timed events running when actors are recycled

Universal.hx
=> Fix: Scale modes swapped.

com/stencyl/Engine.hx
Fix issue here: http://community.stencyl.com/index.php/topic,40153.msg262518.html#new
=> Fix: Full screen when using scale other than 1x

Universal.hx
Fix the issue mentioned here:
http://community.stencyl.com/index.php/topic,47337.0.html
=> Fix "Scale to Fit (Full Screen)" scale issue.

Universal.hx
Fix issue here: http://community.stencyl.com/index.php/topic,40153.msg263346.html#new
Also some more work on scaling. I decided to add integer scales for non 1x scale modes, rather than integer multiples of the scale mode (although I believe this is a 1 line change).
=> Fix: No scale when using non 1x scale

com/stencyl/models/scene/Layer.hx
See: http://community.stencyl.com/index.php/topic,46607.new.html#new for demonstrations of what has been done.
=> Fix: Layer rendering without pixel snapping

com/stencyl/models/Actor.hx
http://community.stencyl.com/index.php?issue=328.0
=>  Mouse Over Scaled Rotated Actor bug

Universal.hx, com/stencyl/Engine.hx
Fix here: http://community.stencyl.com/index.php?issue=363.0
=> Fix scaling using Scale to fit (full screen)

Universal.hx, com/stencyl/Engine.hx
Clearly my most recent changes provided more hassle than it helped, so I've reverted back both files to how they were before these changes and I will try to fix the original issue in a nicer way.
=> Revert to pre-buggy changes

com/stencyl/models/Actor.hx
Fixing this issue: http://community.stencyl.com/index.php/topic,47656.0.html
=> Add pausing of tweens

com/stencyl/models/collision/Masklist.hx
Just another problem with initialising a variable as 0 which took an annoying amount of time to find.
=> Fix simple physics for HTML5

Universal.hx
http://community.stencyl.com/index.php?issue=370.0
Maybe the fixes that LetMeThink removed later work. This was the problem it seems.
=> Update Universal.hx Fix scale

README.md
A little update to help future people with this same question.
=> README.md; instructions on working with a dev fork

com/stencyl/behavior/Script.hx
Just correcting  convertingToPseudoUnicode by using unifill integrated in Lime.
=> correcting convertingToPseudoUnicode
